installed.packages("cairo")
installed.packages("visualize")
library("cairo")
library(visualize)
set.seed(6)
plot (x,y)
attach(mtcars)
layout(matrix(2:1,1 , 2, byrow = T))
hist(x, col="peachpuff", border="black", prob = TRUE, xlab="temp", main = "Beaver #2")
lines(density(x), col="red", lwd =2)
curve(dnorm(x, mean = mean(x), sd = sd(x)), col = "darkblue", lwd = 2, add = T)
hist(y, col="peachpuff", border="black", prob = TRUE, xlab="temp", main = "Beaver #1")
lines(density(y), col="red", lwd =2)
curve(dnorm(y, mean = mean(y), sd = sd(y)), col = "darkblue", lwd = 2, add = T, xname = "y")
detach(mtcars)

